title: Emilie Josephson 
description: MEML Student with background in Industrial Engineering and Economics. Industry experience related to process and systems engineering in biotechnology and energy. 
theme: jekyll-theme-tactile
