title: Emilie Josephson 
description: Master of Engineering Management and Leadership (MEML) student with a strong foundation in Industrial Engineering and Economics. Proven industry experience in process optimization and systems engineering, with a focus on energy and biotechnology sectors. 
theme: jekyll-theme-time-machine
